server:
  port: 8887

spring:
  application:
    name: taco-cloud
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML
